FROM getmeili/meilisearch:v1.14 AS meilisearch

FROM node:24-alpine

# Take mailisearch from getmeili/meilisearch.
COPY --from=meilisearch /bin/meilisearch /usr/local/bin/meilisearch

# Install Google Cloud CLI.
ARG GOOGLE_CLOUD_CLI_VERSION=522.0.0

RUN <<EOF
apk add --no-cache python3 curl jq
curl --silent https://storage.googleapis.com/cloud-sdk-release/google-cloud-cli-${GOOGLE_CLOUD_CLI_VERSION}-linux-x86_64.tar.gz | tar zxf - -C /opt
/opt/google-cloud-sdk/install.sh --quiet
EOF

# File locations.
ENV PATH="/opt/google-cloud-sdk/bin:$PATH"
ENV SEARCH_DIR=/search
ENV SEARCH_DB=${SEARCH_DIR}/data.ms
ARG APP_DIR=/app

#COPY /meili_data/dumps/20250120-081408619.dump /meili_data/dumps/latest.dump

WORKDIR ${APP_DIR}
COPY package.json package-lock.json ${APP_DIR}

RUN <<EOF
npm install
npm install -y tsx
EOF

COPY . ${APP_DIR}
WORKDIR ${APP_DIR}

ENTRYPOINT ["/app/tools/search/recreate_index.sh"]
