# The base image is Google Cloud's CLI image, because adding Node on
# this image would be slightly more straightforward than adding
# the CLI to node image.
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:489.0.0-stable

RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends npm curl
rm -rf /var/lib/apt/lists/*
EOF

# File locations.
ENV SEARCH_DIR=/search
ENV SEARCH_DB=${SEARCH_DIR}/data.ms
ARG APP_DIR=/app

#COPY /meili_data/dumps/20250120-081408619.dump /meili_data/dumps/latest.dump

WORKDIR ${SEARCH_DIR}
RUN <<EOF
curl -L https://install.meilisearch.com | sh
EOF

WORKDIR ${APP_DIR}
COPY package.json package-lock.json ${APP_DIR}

RUN <<EOF
npm install
npm install -y tsx
EOF

COPY . ${APP_DIR}
WORKDIR ${APP_DIR}

ENTRYPOINT ["/app/tools/search/recreate_index.sh"]
