on:
  pull_request:
  push:
      branches:
        - main
permissions:
  checks: write
  contents: read
  pull-requests: write
  packages: write
  id-token: write

jobs:
  build-index:
    name: Build index
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/index
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
        id: build
        with:
          file: Dockerfile.index
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
      - uses: google-github-actions/auth@v2
        with:
          project_id: sps-by-the-numbers
          workload_identity_provider: projects/319988578351/locations/global/workloadIdentityPools/github/providers/github-oidc
          service_account: github-action-716919134@sps-by-the-numbers.iam.gserviceaccount.com
      - uses: google-github-actions/deploy-cloudrun@v2
        if: github.event_name == 'push'
        with:
          job: meilisearch-index
          image: us-west1-docker.pkg.dev/sps-by-the-numbers/ghcr/sps-by-the-numbers/index@${{ steps.build.outputs.digest }}
          region: us-west1
          labels: ${{ steps.meta.outputs.labels }}

  build-search:
    name: Build search
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/search
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
        with:
          file: Dockerfile.search
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

