on:
  pull_request:
  push:
      branches:
        - main
permissions:
  checks: write
  contents: read
  pull-requests: write
  packages: write

jobs:
  build-index:
    name: Build index
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/index
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
        with:
          file: Dockerfile.index
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
