on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
  packages: write

jobs:
  build_and_test:
    name: Deploy to Firebase Hosting on PR
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    uses: ./.github/workflows/build-all.yml

  # docker/build-push-action's inputs are documented in
  # https://github.com/docker/build-push-action?tab=readme-ov-file#inputs

  build-transcribe-worker:
    name: Build transcribe-worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
        with:
          context: tools/process_new_vids
          push: false
          tags: transcribe-worker

  build-search:
    name: Build search
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
        with:
          file: Dockerfile.search
          push: false
          tags: search

  build-index:
    name: Build index
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/index
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
        with:
          file: Dockerfile.index
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
